### ISSUE TITLE
Calling `getNextSiblingElement` when there isn't another sibling causes the process to crash

### ISSUE THREAD

**Issue by jakecyr** [bright-fish/node-ui-automation#1]
Process crashes with error
77 Segmentation fault

**Comment by bright-fish** [comment]
Looking into this to see if it is still an issue.

**Comment by bright-fish** [comment]
This must have been on a previous version that had a bug.  In the current version it returns null, which is expected, and to follow through if you invoke getNextSiblingElement with the null value it errors with `Cannot convert undefined or null to object`.  I think this is not an issue with the current version.
